# Generated by Django 2.1.4 on 2018-12-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Khach_hang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=264)),
                ('ten_dang_nhap', models.CharField(max_length=50)),
                ('mat_khau', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=264)),
                ('dia_chi', models.TextField(max_length=264)),
            ],
            options={
                'db_table': 'Khachhang',
            },
        ),
    ]
